name: Prelab08 CI

on:
  push:
    branches:
      - main
      - master
      - '**'   # run on all branches
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      # Step 4: Run tests with coverage
      - name: Run tests and generate coverage report
        run: |
          pytest -q --cov=src --cov-report=term-missing